FROM ubuntu:20.04

# Install OS Packages
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
RUN pip3 install --upgrade pip
 
# Copy Source Code
WORKDIR /MythicalMysfitsService
COPY ./service .

# Install Python Packages 
RUN pip install -r ./requirements.txt

# Configure Run Commands
ENTRYPOINT ["python3"]
CMD ["mythicalMysfitsService.py"]