FROM ubuntu:latest

# Install OS Packages
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
RUN pip3 install --upgrade pip
 
# Copy Source Code
COPY ./service /MythicalMysfitsService

# Install Python Packages 
WORKDIR /MythicalMysfitsService
RUN pip install -r ./requirements.txt

# Expose the Application
EXPOSE 8080
 
# Configure Run Commands
ENTRYPOINT ["python3"]
CMD ["mythicalMysfitsService.py"]